[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold]
style = "SemiBold"

[font.bold_italic]
style = "SemiBold Italic"

[font.italic]
style = "ExtraLight Italic"

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 0
y = 1
