#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 06
yabai -m config bottom_padding 06
yabai -m config left_padding 06
yabai -m config right_padding 06
yabai -m config window_gap 06

# Float all windows that are not resizeable
# https://github.com/koekeishiya/yabai/issues/924#issuecomment-859727411
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" == false and .\"is-floating\" == false" && yabai -m window $YABAI_WINDOW_ID --toggle float'

# Workaround for retiling going so crazy
# https://github.com/koekeishiya/yabai/issues/2321
yabai -m signal --add event=window_resized action='sleep 1'
yabai -m signal --add event=window_moved action='sleep 1'

# Float the Fantastical menubar popup
yabai -m rule --add app="^Fantastical Helper$" manage=off

# Float every Godot window except the godot editor itself
yabai -m rule --add app="^Godot$" title!="Godot Engine" manage=off #layer=above
# Float every Darktable window except the main one
yabai -m rule --add app="^darktable$" title!="^darktable$" manage=off

yabai -m config debug_output on

echo "yabai configuration loaded.."
