" Settings for gitconfig files

" Only execute this script once for the current buffer
if exists("b:gitconfig_ftplugin_loaded")
  finish
endif
let b:gitconfig_ftplugin_loaded = 1

" Use tabs to match configuration generated by 'git config' command.
setlocal tabstop=4 shiftwidth=4 noexpandtab
